title: Azellaz
exclude: [whiteboard.md]
api_key: NjQyNTJmYzUtZGY3Yy00MzE1LTk5ZGUtMmYwN2ZhZjYxYmQyNjM2MjQyNjk5MDU5MDI2MjE2
base_url: https://azellaz.com/
images_dir: images/launch-photos-edited-imageOptimized/
etsy: https://www.etsy.com/shop/Azellaz
instagram: https://www.instagram.com/azellaz/
github: https://github.com/brianzelip/Azellaz.com
email: support@azellaz.com
