gems:
  - jekyll-sitemap

title: Azellaz
tagline: Quality bags built from scratch in Baltimore
exclude: [whiteboard.md, test.html, node_modules/, archive/, images/raw-dog-and-others/]
test_api_key: NjQyNTJmYzUtZGY3Yy00MzE1LTk5ZGUtMmYwN2ZhZjYxYmQyNjM2MjQyNjk5MDU5MDI2MjE2
live_api_key: NmJjMmI5YTQtNmNlYy00YzJmLWE0NjUtZDQ0YzE5NWQ3YmYzNjM2MjQyNjk5MDU5MDI2MjE2
base_url: https://www.azellaz.com/
bas_url_no_trailing_slash: https://www.azellaz.com
images_dir: images/
product_images_dir: images/products/
product_thumb_sm_images_dir: images/products/thumbs-sm/
product_thumb_med_images_dir: images/products/thumbs-med/
thumb_medium_prefix: thumb-med-
featured_bag_image: indigo-shibori-duffle-front-by-Azellaz.jpg
etsy: https://www.etsy.com/shop/Azellaz
instagram: https://www.instagram.com/azellaz/
github: https://github.com/brianzelip/Azellaz.com
email: support@azellaz.com
in_stock: This item is in stock and ready to ship. Items are individually dyed and may vary slightly from these images.
made_to_order: Made to order, ships in 1-3 weeks. Items are individually dyed and may vary slightly from these images.
flash_holiday_order_by: Order by Tuesday, December 12 to ship in time for Christmas.
flash_holiday_orders_from_now: Orders placed today will be shipped in January 2018. Happy holidays!
