title: Azellaz
exclude: [whiteboard.md, test.html]
test_api_key: NjQyNTJmYzUtZGY3Yy00MzE1LTk5ZGUtMmYwN2ZhZjYxYmQyNjM2MjQyNjk5MDU5MDI2MjE2
live_api_key: NmJjMmI5YTQtNmNlYy00YzJmLWE0NjUtZDQ0YzE5NWQ3YmYzNjM2MjQyNjk5MDU5MDI2MjE2
base_url: https://www.azellaz.com/
images_dir: images/launch-photos-edited-imageOptimized/
etsy: https://www.etsy.com/shop/Azellaz
instagram: https://www.instagram.com/azellaz/
github: https://github.com/brianzelip/Azellaz.com
email: support@azellaz.com
in_stock: This item is in stock and ready to ship. Each item is individually dyed and may vary slightly from these images.
made_to_order: Made to order, ships in 1-3 weeks. Each item is individually dyed and may vary slightly from these images.
