backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)
media_folder: 'images/uploads'
site_url: https://dev--azellaz.netlify.com/
collections:
  - label: 'Products'
    name: 'products'
    folder: 'cms'
    create: true
    identifier_field: displayName
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'product',
        }
      - { label: 'Name', name: 'displayName', widget: 'string' }
      - {
          label: 'Include item in shop?',
          name: 'currentListing',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Is currently in stock?',
          name: 'inStock',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Number of stock currently on hand',
          name: 'stockOnHand',
          widget: 'number',
          valueType: 'int',
          default: 0,
        }
      - { label: 'id', name: 'id', widget: 'string' }
      - { label: 'slug', name: 'slug', widget: 'string' }
      - { label: 'url', name: 'url', widget: 'string' }
      - { label: 'price', name: 'price', widget: 'number', valueType: 'int' }
      - {
          label: 'Bag type',
          name: 'type',
          widget: 'select',
          options:
            [
              'backpack',
              'circular pouch',
              'clutch',
              'crossbody',
              'duffle',
              'medium tote',
              'small tote',
            ],
        }
      - {
          label: 'Materials',
          name: 'materials',
          widget: 'select',
          multiple: true,
          options: ['felt', 'leather', 'waxed canvas'],
        }
      - { label: 'Short description', name: 'descriptionShort', widget: 'text' }
      - { label: 'Long description', name: 'descriptionLong', widget: 'text' }
      - { label: 'Weight', name: 'weight', widget: 'number', valueType: 'int' }
      - { label: 'Height', name: 'height', widget: 'number', valueType: 'int' }
      - { label: 'Width', name: 'width', widget: 'number', valueType: 'int' }
      - { label: 'Length', name: 'length', widget: 'number', valueType: 'int' }
      - {
          label: 'Primary image',
          name: 'imgPrimary',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          label: 'Set of secondary images',
          name: 'imgSecondarySet',
          widget: 'image',
          allow_multiple: true,
        }
