backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)
media_folder: 'images/uploads'
site_url: https://dev--azellaz.netlify.com/
collections:
  - label: 'Products'
    name: 'products'
    folder: 'cms'
    create: true
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'product',
        }
      - { label: 'id', name: 'id', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
      - { label: 'Display name', name: 'displayName', widget: 'string' }
      - { label: 'slug', name: 'slug', widget: 'string' }
      - { label: 'url', name: 'url', widget: 'string' }
      - { label: 'Is in stock?', name: 'inStock', widget: 'boolean' }
      - { label: 'stockOnHand', name: 'stockOnHand', widget: 'number' }
      - { label: 'price', name: 'price', widget: 'number' }
      - {
          label: 'Type',
          name: 'type',
          widget: 'select',
          options:
            [
              'backpack',
              'circular pouch',
              'clutch',
              'crossbody',
              'duffle',
              'medium tote',
              'small tote',
            ],
        }
      - {
          label: 'Materials',
          name: 'materials',
          widget: 'select',
          multiple: true,
          options: ['felt', 'leather', 'waxed canvas'],
        }
      - {
          label: 'Include item in shop?',
          name: 'currentListing',
          widget: 'boolean',
        }
      - { label: 'Short description', name: 'descriptionShort', widget: 'text' }
      - { label: 'Long description', name: 'descriptionLong', widget: 'text' }
      - { label: 'Weight', name: 'weight', widget: 'number' }
      - { label: 'Height', name: 'height', widget: 'number' }
      - { label: 'Width', name: 'width', widget: 'number' }
      - { label: 'Length', name: 'length', widget: 'number' }
      - {
          label: 'Primary image',
          name: 'imgPrimary',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          label: 'Set of secondary images',
          name: 'imgSecondarySet',
          widget: 'image',
        }
