backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)
media_folder: 'images/uploads'
site_url: https://dev--azellaz.netlify.com/
collections:
  - label: 'Products'
    name: 'products'
    folder: 'cms'
    create: true
    identifier_field: name
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'product'
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Full display name',
          name: 'displayName',
          widget: 'string',
          required: false,
        }
      - { label: 'id', name: 'id', widget: 'string', default: 'AZ00' }
      - label: 'Include item in shop?'
        name: 'currentListing'
        widget: 'boolean'
        default: false
      - label: 'Is currently in stock?'
        name: 'inStock'
        widget: 'boolean'
        default: false
      - label: 'Number of stock currently on hand'
        name: 'stockOnHand'
        widget: 'number'
        valueType: 'int'
        default: 0
      - label: 'Bag type'
        name: 'type'
        widget: 'select'
        options:
          [
            'backpack',
            'circular pouch',
            'clutch',
            'crossbody',
            'duffle',
            'medium tote',
            'small tote',
          ]
        required: false
      - label: 'Short description'
        name: 'descriptionShort'
        widget: 'text'
        required: false
      - label: 'Long description'
        name: 'descriptionLong'
        widget: 'text'
        required: false
      - label: 'Materials'
        name: 'materials'
        widget: 'select'
        multiple: true
        options: ['felt', 'leather', 'waxed canvas']
        required: false
      - label: 'price'
        name: 'price'
        widget: 'number'
        valueType: 'int'
        required: false
      - label: 'Weight'
        name: 'weight'
        widget: 'number'
        valueType: 'int'
        required: false
      - label: 'Height'
        name: 'height'
        widget: 'number'
        valueType: 'int'
        required: false
      - label: 'Width'
        name: 'width'
        widget: 'number'
        valueType: 'int'
        required: false
      - label: 'Length'
        name: 'length'
        widget: 'number'
        valueType: 'int'
        required: false
      - label: 'Primary photo'
        name: 'imgPrimary'
        widget: 'image'
        allow_multiple: false
        required: false
      - label: 'Secondary photos'
        name: 'imgSecondarySet'
        widget: 'list'
        allow_multiple: true
        field: { label: Image, name: image, widget: image }
        required: false
